name: Deploy Vue.js App to Docker

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch
  pull_request:
    branches:
      - main  # Optional: Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the appropriate Node.js version for your project

    - name: Install dependencies
      run: |
        npm install  # or yarn install if you use Yarn

    - name: Build the project
      run: |
        npm run build  # or yarn build if you use Yarn

        - name: Deploy to Docker container on server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Create SSH Key and Connect to Server
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
  
          # Copy build files to the host machine (not inside the container)
          scp -i private_key -o StrictHostKeyChecking=no -r dist/* mageta@41.220.139.164:/home/mageta/projects/laravel-vue-project/frontend/dist
  
          # Restart the Docker container to serve new files
          ssh -i private_key -o StrictHostKeyChecking=no mageta@41.220.139.164 << 'EOF'
            cd /home/mageta/projects/laravel-vue-project
            docker-compose restart node
          EOF
